import { ArrowDownRight, ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { artist, platformLinks, releases } from '../data/demo'
import { Artwork } from '../components/Artwork'
import { PlatformLinks } from '../components/PlatformLinks'
import { useAudioPlayer } from '../context/AudioPlayerContext'
import { useEffect, useState } from 'react'
import { InteractiveIntro } from '../components/InteractiveIntro'
import { fetchArtistPlatformLinks } from '../lib/platformLinks'
import type { PlatformLink } from '../types'

export function Home() { const [introComplete, setIntroComplete] = useState(false); const [links, setLinks] = useState<PlatformLink[]>(platformLinks); const featured = releases.find((release) => release.featured) ?? releases[0]; const latest = releases[1]; const { setQueue, playTrack } = useAudioPlayer(); const latestTracks = latest.tracks.map((track) => ({ ...track, artwork: latest.artwork, artistName: artist.name })); useEffect(() => { void fetchArtistPlatformLinks(artist.id).then(setLinks) }, []); return <><InteractiveIntro artistName={artist.name} onComplete={() => setIntroComplete(true)} /><div className={`page home-page ${introComplete ? 'home-is-visible' : 'home-is-hidden'}`} aria-hidden={!introComplete}><section className="hero"><div className="hero-index">01 / 04</div><h1>{artist.name}</h1><p className="hero-note">Music for<br />in-between places.</p><ArrowDownRight className="hero-arrow" size={30} /></section><section className="feature-grid"><div className="feature-copy"><p className="eyebrow">Featured release / 01</p><h2>{featured.title}</h2><p>{featured.description}</p><Link className="text-link" to={`/releases/${featured.id}`}>Explore release <ArrowUpRight size={14} /></Link></div><Link to={`/releases/${featured.id}`}><Artwork src={featured.artwork} title={featured.title} accent={featured.accent} className="feature-art" /></Link></section><section className="latest-section"><div className="section-heading"><p className="eyebrow">Latest</p><Link className="text-link" to="/releases">View all <ArrowUpRight size={14} /></Link></div><div className="latest-row"><Artwork src={latest.artwork} title={latest.title} accent={latest.accent} className="latest-art" /><div className="latest-detail"><span className="release-number">02</span><h3>{latest.title}</h3><p>{latest.type} / {new Date(latest.releaseDate).getFullYear()}</p><button className="circle-action" onClick={() => { setQueue(latestTracks); playTrack(latestTracks[0]) }} aria-label={`Play ${latest.title}`}><span>Play</span> ↗</button></div></div></section><section className="platforms" id="platforms"><div><p className="eyebrow">Find the music</p><h2>Out in the world.</h2></div><PlatformLinks links={links} /></section></div></> }